import ctypes

# Constants
AC_PLUGIN_VERSION = 1

class SPageFilePhysics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('packetId', ctypes.c_int),
        ('gas', ctypes.c_float),
        ('brake', ctypes.c_float),
        ('fuel', ctypes.c_float),
        ('gear', ctypes.c_int),
        ('rpms', ctypes.c_int),
        ('steerAngle', ctypes.c_float),
        ('speedKmh', ctypes.c_float),
        ('velocity', ctypes.c_float * 3),
        ('accG', ctypes.c_float * 3),
        ('wheelSlip', ctypes.c_float * 4),
        ('wheelLoad', ctypes.c_float * 4),
        ('wheelsPressure', ctypes.c_float * 4),
        ('wheelAngularSpeed', ctypes.c_float * 4),
        ('tyreWear', ctypes.c_float * 4),
        ('tyreDirtyLevel', ctypes.c_float * 4),
        ('tyreCoreTemperature', ctypes.c_float * 4),
        ('camberRAD', ctypes.c_float * 4),
        ('suspensionTravel', ctypes.c_float * 4),
        ('drs', ctypes.c_float),
        ('tc', ctypes.c_float),
        ('heading', ctypes.c_float),
        ('pitch', ctypes.c_float),
        ('roll', ctypes.c_float),
        ('cgHeight', ctypes.c_float),
        ('carDamage', ctypes.c_float * 5),
        ('numberOfTyresOut', ctypes.c_int),
        ('pitLimiterOn', ctypes.c_int),
        ('abs', ctypes.c_float),
        ('kersCharge', ctypes.c_float),
        ('kersInput', ctypes.c_float),
        ('autoShifterOn', ctypes.c_int),
        ('rideHeight', ctypes.c_float * 2),
        ('turboBoost', ctypes.c_float),
        ('ballast', ctypes.c_float),
        ('airDensity', ctypes.c_float),
        ('airTemp', ctypes.c_float),
        ('roadTemp', ctypes.c_float),
        ('localAngularVel', ctypes.c_float * 3),
        ('finalFF', ctypes.c_float),
        ('performanceMeter', ctypes.c_float),
        ('engineBrake', ctypes.c_int),
        ('ersRecoveryLevel', ctypes.c_int),
        ('ersPowerLevel', ctypes.c_int),
        ('ersHeatCharging', ctypes.c_int),
        ('ersIsCharging', ctypes.c_int),
        ('kersCurrentKJ', ctypes.c_float),
        ('drsAvailable', ctypes.c_int),
        ('drsEnabled', ctypes.c_int),
        ('brakeTemp', ctypes.c_float * 4),
        ('clutch', ctypes.c_float),
        ('tyreTempI', ctypes.c_float * 4),
        ('tyreTempM', ctypes.c_float * 4),
        ('tyreTempO', ctypes.c_float * 4),
        ('isAIControlled', ctypes.c_int),
        ('tyreContactPoint', ctypes.c_float * 4 * 3),
        ('tyreContactNormal', ctypes.c_float * 4 * 3),
        ('tyreContactHeading', ctypes.c_float * 4 * 3),
        ('brakeBias', ctypes.c_float),
        ('localVelocity', ctypes.c_float * 3),
        ('P2PActivations', ctypes.c_int),
        ('P2PStatus', ctypes.c_int),
        ('currentMaxRpm', ctypes.c_int),
        ('mz', ctypes.c_float * 4),
        ('fx', ctypes.c_float * 4),
        ('fy', ctypes.c_float * 4),
        ('slipRatio', ctypes.c_float * 4),
        ('slipAngle', ctypes.c_float * 4),
        ('tcinAction', ctypes.c_int),
        ('absInAction', ctypes.c_int),
        ('suspensionNDamage', ctypes.c_float * 4),
        ('tyreTemp', ctypes.c_float * 4),
    ]

class SPageFileGraphics(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('packetId', ctypes.c_int),
        ('status', ctypes.c_int), # AC_STATUS enum
        ('session', ctypes.c_int), # AC_SESSION_TYPE enum
        ('currentTime', ctypes.c_wchar * 15),
        ('lastTime', ctypes.c_wchar * 15),
        ('bestTime', ctypes.c_wchar * 15),
        ('split', ctypes.c_wchar * 15),
        ('completedLaps', ctypes.c_int),
        ('position', ctypes.c_int),
        ('iCurrentTime', ctypes.c_int),
        ('iLastTime', ctypes.c_int),
        ('iBestTime', ctypes.c_int),
        ('sessionTimeLeft', ctypes.c_float),
        ('distanceTraveled', ctypes.c_float),
        ('isInPit', ctypes.c_int),
        ('currentSectorIndex', ctypes.c_int),
        ('lastSectorTime', ctypes.c_int),
        ('numberOfLaps', ctypes.c_int),
        ('tyreCompound', ctypes.c_wchar * 33),
        ('replayTimeMultiplier', ctypes.c_float),
        ('normalizedCarPosition', ctypes.c_float),
        ('activeCars', ctypes.c_int),
        ('carCoordinates', ctypes.c_float * 60 * 3),
        ('carID', ctypes.c_int * 60),
        ('playerCarID', ctypes.c_int),
        ('penaltyTime', ctypes.c_float),
        ('flag', ctypes.c_int), # AC_FLAG_TYPE enum
        ('penalty', ctypes.c_int), # AC_PENALTY_TYPE enum
        ('idealLineOn', ctypes.c_int),
        ('isInPitLane', ctypes.c_int),
        ('surfaceGrip', ctypes.c_float),
        ('mandatoryPit', ctypes.c_int),
        ('windSpeed', ctypes.c_float),
        ('windDirection', ctypes.c_float),
        ('isSetupMenuVisible', ctypes.c_int),
        ('mainDisplayIndex', ctypes.c_int),
        ('secondaryDisplayIndex', ctypes.c_int),
        ('TC', ctypes.c_int),
        ('TCCut', ctypes.c_int),
        ('EngineMap', ctypes.c_int),
        ('ABS', ctypes.c_int),
        ('fuelXLap', ctypes.c_float),
        ('rainLights', ctypes.c_int),
        ('flashingLights', ctypes.c_int),
        ('lightsStage', ctypes.c_int),
        ('exhaustTemperature', ctypes.c_float),
        ('wiperLV', ctypes.c_int),
        ('DriverStintTotalTimeLeft', ctypes.c_int),
        ('DriverStintTimeLeft', ctypes.c_int),
        ('rainTyres', ctypes.c_int),
    ]

class SPageFileStatic(ctypes.Structure):
    _pack_ = 4
    _fields_ = [
        ('smVersion', ctypes.c_wchar * 15),
        ('acVersion', ctypes.c_wchar * 15),
        ('numberOfSessions', ctypes.c_int),
        ('numCars', ctypes.c_int),
        ('carModel', ctypes.c_wchar * 33),
        ('track', ctypes.c_wchar * 33),
        ('playerName', ctypes.c_wchar * 33),
        ('playerSurname', ctypes.c_wchar * 33),
        ('playerNick', ctypes.c_wchar * 33),
        ('sectorCount', ctypes.c_int),
        ('maxTorque', ctypes.c_float),
        ('maxPower', ctypes.c_float),
        ('maxRpm', ctypes.c_int),
        ('maxFuel', ctypes.c_float),
        ('suspensionMaxTravel', ctypes.c_float * 4),
        ('tyreRadius', ctypes.c_float * 4),
        ('maxTurboBoost', ctypes.c_float),
        ('deprecated_1', ctypes.c_float),
        ('deprecated_2', ctypes.c_float),
        ('penaltiesEnabled', ctypes.c_int),
        ('aidFuelRate', ctypes.c_float),
        ('aidTireRate', ctypes.c_float),
        ('aidMechanicalDamage', ctypes.c_float),
        ('allowTyreBlankets', ctypes.c_int),
        ('aidStability', ctypes.c_float),
        ('aidAutoClutch', ctypes.c_int),
        ('aidAutoBlip', ctypes.c_int),
        ('hasDRS', ctypes.c_int),
        ('hasERS', ctypes.c_int),
        ('hasKERS', ctypes.c_int),
        ('kersMaxJ', ctypes.c_float),
        ('engineBrakeSettingsCount', ctypes.c_int),
        ('ersPowerControllerCount', ctypes.c_int),
        ('trackSplineLength', ctypes.c_float),
        ('trackConfiguration', ctypes.c_wchar * 33),
        ('ersMaxJ', ctypes.c_float),
        ('isTimedRace', ctypes.c_int),
        ('hasExtraLap', ctypes.c_int),
        ('carSkin', ctypes.c_wchar * 33),
        ('reversedGridPositions', ctypes.c_int),
        ('pitWindowStart', ctypes.c_int),
        ('pitWindowEnd', ctypes.c_int),
        ('isOnline', ctypes.c_int),
    ]

AC_STATUS_OFF = 0
AC_STATUS_REPLAY = 1
AC_STATUS_LIVE = 2
AC_STATUS_PAUSE = 3
